<!doctype html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
    </head>
	
    <body>
		<header class="header">
			<h1><a href="/" rel="home">Ranking kredytów gotówkowych</a></h1>
		</header>
        
		<?php include($content); ?>
        
		<footer class="footer">
			<div class="container">
				<p class="copyrights">
					Copyright © 2015
				</p>
			</div>
		</footer>
    </body>
</html>