<!doctype html>
<html lang="pl">
    <head>
      <meta charset="utf-8">
      <title>Projekt WSTI - Ranking kredytów gotówkowych</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <!-- Loading Bootstrap -->
      <link href="../../dist/css/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

      <!-- Loading Flat UI -->
      <link href="../../dist/css/flat-ui.min.css" rel="stylesheet">

      <link rel="shortcut icon" href="../../public/dist/img/favicon.ico">

      <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
      <!--[if lt IE 9]>
        <script src="../../public/dist/js/vendor/html5shiv.js"></script>
        <script src="../../public/dist/js/vendor/respond.min.js"></script>
      <![endif]-->
    </head>
	
    <body>
                        <div class="container">
		<div class="row">
                    <div class="span10">
                        <h1 style="padding-bottom: 20px;"><a href="/" rel="home">Ranking kredytów gotówkowych</a>
                            <img class="pull-right" alt="Clipboard" src="../dist/img/icons/svg/clipboard.svg">
                        </h1>
                    </div>
                </div>
                    
		<?php include($content); ?>
        
                        </div>
                            
		<footer class="footer">
			<div class="container">
				<p class="copyrights" style="padding-top: 10px">
					Copyright © 2015
				</p>
			</div>
		</footer>
                            
    </body>
    <!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
    <script src="../../dist/js/vendor/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../dist/js/vendor/video.js"></script>
    <script src="../../dist/js/flat-ui.min.js"></script>
</html>