<form method="post">
	<?php if(!$valid): ?>W formularzu znajduje się błąd. Popraw go i spróbuj ponownie.<?php endif; ?>

	<input type="hidden" name="application_offer" value="<?= $offer->offer_id; ?>">

	<div>
		<label for="firstname">Imię</label>
		<input type="text" name="application_firstname" id="fistname" placeholder="Imię" required>
	</div>
	
	<div>
		<label for="lastname">Nazwisko</label>
		<input type="text" name="application_lastname" id="lastname" placeholder="Nazwisko" required>
	</div>
	
	<div>
		<label for="pesel">PESEL</label>
		<input type="text" name="application_pesel" id="pesel" placeholder="PESEL" required>
	</div>
	
	<div>
		<label for="email">Email</label>
		<input type="email" name="application_email" id="email" placeholder="Email" required>
	</div>
	
	<div>
		<label for="phone">Telefon</label>
		<input type="text" name="application_phone" id="phone" placeholder="Telefon" required>
	</div>
	
	<button type="submit">Wyślij wniosek</button>
</form>